[build]
  publish = "my_smart_home_web/dist"
  command = "source build_api.sh && cd my_smart_home_web && source build.sh"
  functions = "dist/api"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
